version: "3.9"

services:
  spark-master:
    image: bitnami/spark:latest
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - sparknet
    environment:
      - SPARK_MODE=master
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  spark-worker:
    image: bitnami/spark:latest
    ports:
      - "7078:7078"
      - "7079:7079"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    networks:
      - sparknet

networks:
  sparknet:
    external: true

#  bridge:
#    name: bridge
#    external: true