version: '3.8'
services:
  sparkmaster:
    build: .
    ports:
      - "8080:8080"
      - "7077:7077"
    command: /usr/local/spark/sbin/start-master.sh --host sparkmaster
    networks:
       group1net:
        ipv4_address: 10.0.1.6
  sparkworker:
    build: .
    ports:
      - "8081:8081"
    command: /usr/local/spark/sbin/start-slave.sh spark://sparkmaster:7077
    networks:
       group1net:
        ipv4_address: 10.0.1.5
networks:
  group1net:
    ipam:
      config:
        - subnet: 10.0.1.0/24


    