FROM ubuntu:22.04
# Dockerfile for container running a Spark Worker in the Kubernetes cluster
# Spark Master node is exposed as sparknet:7077 using a clusterIP service
#
# dependencies
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y openjdk-11-jdk-headless
RUN apt-get install -y scala
RUN apt-get install -y wget
RUN apt-get install -y screen
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
# spark
ADD https://archive.apache.org/dist/spark/spark-3.2.3/spark-3.2.3-bin-hadoop3.2.tgz .
RUN tar xvf spark-3.2.3-bin-hadoop3.2.tgz
RUN mv spark-3.2.3-bin-hadoop3.2/ /usr/local/spark
RUN rm spark-3.2.3-bin-hadoop3.2.tgz
ENV PATH=${PATH}:$SPARK_HOME/bin
ENV SPARK_HOME=/usr/local/spark
ENV SPARK_NO_DAEMONIZE=true
CMD $SPARK_HOME/sbin/start-worker.sh spark://sparknet:7077
